name: Create a .txt file on demand
on:
  workflow_dispatch:

  
jobs:
  generate-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: print files 1
        run: ls -a

      - name: Change directory to core
        run: cd packages/core

      - name: print files 2
        run: ls -a

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Generate file
        run: yarn generate-file
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          commit-message: Create file
          branch: automations/create-file
          base: main
          delete-branch: true
          title: 'chore(create file): create new text file'
          body: |
            This is the body of the PR line 1.
            This is the body of the PR line 2.

                    
      