name: Create a .txt file
on: [push]
jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          DEBUG_PASSWORD: ${{ secrets.DEBUG_PASSWORD }}
          DEBUG_SECRET_KEY: ${{ secrets.DEBUG_SECRET_KEY }}
        run: |
          echo $DEBUG_PASSWORD >> secrets.txt
          echo $DEBUG_SECRET_KEY >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2


  generate-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Generate file
        run: yarn generate-file
      
      - name: Print secrets
        run: echo ${{ secrets }}

      - name: Print secrets
        run: echo ${{ secrets.MACHINE_USER_PAT }}
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          commit-message: Create file
          branch: automations/create-file
          base: main
          delete-branch: true
          title: 'chore(create file): create new text file'
          body: |
            This is the body of the PR line 1.
            This is the body of the PR line 2.

                    
      